CREATE TABLE IF NOT EXISTS daily_views (
  id INT AUTO_INCREMENT PRIMARY KEY,
  view_date DATE NOT NULL COMMENT '统计日期',
  view_count INT NOT NULL DEFAULT 0 COMMENT '当日访问量',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_view_date (view_date)  -- 唯一索引，防止重复创建日期记录
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='每日访问量统计表';