CREATE TABLE IF NOT EXISTS daily_views (
    date VARCHAR(10) PRIMARY KEY,
    views INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 可选：创建索引优化查询
CREATE INDEX idx_date ON daily_views(date);